services:
  - type: web
    name: kanmind-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python manage.py migrate && python create_superuser.py && python manage.py collectstatic --no-input && gunicorn kanmind.wsgi:application"
    envVars:
      - key: DEBUG
        value: 0
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: yunus@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: Admin123456!