"""
Django settings for kanmind project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""


"""
Zentrale Django-Konfigurationsdatei für das KanMind-Backend.

Hier werden globale Einstellungen wie:
- installierte Apps
- Middleware
- Datenbank
- Authentifizierung
- CORS
definiert.
"""

from pathlib import Path
from dotenv import load_dotenv
import os

# Lädt Umgebungsvariablen aus der .env Datei
load_dotenv()
# Lädt Umgebungsvariablen aus der .env Datei
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/


# ---------------------------
# Sicherheit & Debug
# ---------------------------

# Geheimschlüssel (aus .env, nicht im Code hardcodiert)
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# Debug ist nur für Entwicklung aktiviert
DEBUG = True

# Erlaubte Hosts (lokale Entwicklung)
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]


# ---------------------------
# Installierte Apps
# ---------------------------

INSTALLED_APPS = [
    'corsheaders',  # Ermöglicht CORS für externes Frontend
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "django_extensions",

    "authentication",
    "tasks",
    "boards",

    'rest_framework', # Django REST Framework
    'rest_framework.authtoken', # Django REST Framework
]

# ---------------------------
# Middleware
# ---------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # CORS Support
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Root-URL-Konfiguration
ROOT_URLCONF = 'kanmind.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kanmind.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# SQLite wird für die Entwicklungsphase genutzt
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ---------------------------
# CORS Konfiguration
# ---------------------------

# Erlaubt Zugriff vom externen Frontend (Live Server)

CORS_ALLOWED_ORIGINS = [
  "http://127.0.0.1:5500",
  "http://localhost:5500",
]

CORS_ALLOW_CREDENTIALS = True


# ---------------------------
# Django REST Framework
# ---------------------------

# Standardmäßig Token-Authentifizierung & Login-Pflicht
REST_FRAMEWORK = {
  'DEFAULT_AUTHENTICATION_CLASSES': [
    'rest_framework.authentication.TokenAuthentication',
  ],
  'DEFAULT_PERMISSION_CLASSES': [
    'rest_framework.permissions.IsAuthenticated',
  ],
}